"""Baseline schema.

A static snapshot of the schema as it existed when Alembic was introduced,
generated with ``alembic revision --autogenerate``. On a fresh database this
creates every table and index explicitly. Pre-Alembic databases (created by the
old ``create_all`` path) are *stamped* at this revision by the runner instead of
executing it.

This migration is immutable: it must keep producing the same schema regardless
of later model changes, so it does not call ``Base.metadata.create_all``.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-12
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class _LegacyText(sa.types.TypeDecorator):
    """Frozen DDL snapshot of EncryptedType/Base64Type at baseline time.

    The live application types are TypeDecorators whose DDL could drift with
    future model changes; referencing them here would break this migration's
    immutability contract. On disk they are TEXT on PostgreSQL and VARCHAR on
    SQLite — this pins exactly that.
    """

    impl = sa.String
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(sa.TEXT())
        return dialect.type_descriptor(sa.String())


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("tools_file", sa.TEXT(), nullable=True),
        sa.Column("workflow_file", sa.TEXT(), nullable=True),
        sa.Column("mcp_servers", sa.JSON(), nullable=False),
        sa.Column("skills_dir", sa.TEXT(), nullable=True),
        sa.Column("agents", sa.JSON(), nullable=False),
        sa.Column("planning", sa.Boolean(), nullable=False),
        sa.Column("max_plan_steps", sa.Integer(), nullable=False),
        sa.Column("approve_plan", sa.Boolean(), nullable=False),
        sa.Column("max_tool_calls", sa.Integer(), nullable=False),
        sa.Column("max_concurrent_tools", sa.Integer(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("stream", sa.Boolean(), nullable=False),
        sa.Column("approval_mode", sa.String(), nullable=False),
        sa.Column("reasoning_effort", sa.String(), nullable=True),
        sa.Column("long_term_memory", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "configs",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("external_issuer", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("subject", "external_issuer", name="uix_principal_subject_issuer"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("built_in", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "secrets",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", _LegacyText(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("namespaces", sa.JSON(), nullable=False),
        sa.Column("workflows", sa.JSON(), nullable=False),
        sa.Column("exclusions", sa.JSON(), nullable=False),
        sa.Column("mcp_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "workers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("session_token", sa.String(), nullable=False),
        sa.Column("labels", _LegacyText(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("imports", _LegacyText(), nullable=True),
        sa.Column("source", _LegacyText(), nullable=False),
        sa.Column("requests", _LegacyText(), nullable=True),
        sa.Column("affinity", _LegacyText(), nullable=True),
        sa.Column("wf_metadata", _LegacyText(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint(
            "namespace",
            "name",
            "version",
            name="uix_workflow_namespace_name_version",
        ),
    )
    op.create_index("ix_workflow_namespace_name", "workflows", ["namespace", "name"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("key_hash", name="uix_api_key_hash"),
        sa.UniqueConstraint("principal_id", "name", name="uix_api_key_principal_name"),
    )
    op.create_table(
        "executions",
        sa.Column("execution_id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("workflow_namespace", sa.String(length=64), nullable=False),
        sa.Column("workflow_name", sa.String(), nullable=False),
        sa.Column("input", sa.LargeBinary(), nullable=True),
        sa.Column("output", sa.LargeBinary(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "SCHEDULED",
                "CLAIMED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "PAUSED",
                "RESUMING",
                "RESUME_SCHEDULED",
                "RESUME_CLAIMED",
                "CANCELLING",
                "CANCELLED",
                name="executionstate",
            ),
            nullable=False,
        ),
        sa.Column("worker_name", sa.String(), nullable=True),
        sa.Column("exec_token", sa.String(), nullable=True),
        sa.Column("scheduling_subject", sa.String(), nullable=True),
        sa.Column("scheduling_principal_issuer", sa.String(), nullable=True),
        sa.Column("schedule_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["worker_name"],
            ["workers.name"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("execution_id"),
        sa.UniqueConstraint("execution_id"),
    )
    op.create_index("idx_execution_schedule_id", "executions", ["schedule_id"], unique=False)
    op.create_index("idx_execution_state", "executions", ["state"], unique=False)
    op.create_index(
        "idx_execution_state_worker",
        "executions",
        ["state", "worker_name"],
        unique=False,
    )
    op.create_index("idx_execution_worker_name", "executions", ["worker_name"], unique=False)
    op.create_index(op.f("ix_executions_workflow_id"), "executions", ["workflow_id"], unique=False)
    op.create_index(
        op.f("ix_executions_workflow_name"),
        "executions",
        ["workflow_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executions_workflow_namespace"),
        "executions",
        ["workflow_namespace"],
        unique=False,
    )
    op.create_table(
        "principal_roles",
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("role_name", sa.String(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("principal_id", "role_name"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workflow_id", sa.String(), nullable=False),
        sa.Column("workflow_namespace", sa.String(length=64), nullable=False),
        sa.Column("workflow_name", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("schedule_config", _LegacyText(), nullable=False),
        sa.Column(
            "schedule_type",
            sa.Enum("CRON", "INTERVAL", "ONCE", name="scheduletype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "DISABLED", name="schedulestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("input_data", sa.LargeBinary(), nullable=True),
        sa.Column("run_as_service_account", sa.String(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("workflow_id", "name", name="uix_schedule_workflow_name"),
    )
    op.create_index("idx_schedule_next_run_at", "schedules", ["next_run_at"], unique=False)
    op.create_index("idx_schedule_status", "schedules", ["status"], unique=False)
    op.create_index(
        "idx_schedule_status_next_run",
        "schedules",
        ["status", "next_run_at"],
        unique=False,
    )
    op.create_index("idx_schedule_workflow_id", "schedules", ["workflow_id"], unique=False)
    op.create_table(
        "worker_packages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("worker_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_name"],
            ["workers.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_packages_worker_name"),
        "worker_packages",
        ["worker_name"],
        unique=False,
    )
    op.create_table(
        "worker_resources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cpu_total", sa.Integer(), nullable=False),
        sa.Column("cpu_available", sa.Integer(), nullable=False),
        sa.Column("memory_total", sa.BigInteger(), nullable=False),
        sa.Column("memory_available", sa.BigInteger(), nullable=False),
        sa.Column("disk_total", sa.BigInteger(), nullable=False),
        sa.Column("disk_free", sa.BigInteger(), nullable=False),
        sa.Column("worker_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_name"],
            ["workers.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_resources_worker_name"),
        "worker_resources",
        ["worker_name"],
        unique=False,
    )
    op.create_table(
        "worker_runtimes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("os_name", sa.String(), nullable=False),
        sa.Column("os_version", sa.String(), nullable=False),
        sa.Column("python_version", sa.String(), nullable=False),
        sa.Column("worker_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["worker_name"],
            ["workers.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "agent_sessions",
        sa.Column("execution_id", sa.String(), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("mode", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["executions.execution_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    op.create_index("idx_agent_sessions_agent", "agent_sessions", ["agent_name"], unique=False)
    op.create_index(
        "idx_agent_sessions_agent_started",
        "agent_sessions",
        ["agent_name", "started_at"],
        unique=False,
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("execution_id", sa.String(), nullable=False),
        sa.Column("task_call_id", sa.String(), nullable=False),
        sa.Column("workflow_namespace", sa.String(), nullable=False),
        sa.Column("workflow_name", sa.String(), nullable=False),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "CANCELLED", name="approvalstatus"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approver_subject", sa.String(), nullable=True),
        sa.Column("approver_provider", sa.String(), nullable=True),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.execution_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id", "task_call_id", name="uq_approval_exec_call"),
    )
    op.create_index(
        op.f("ix_approval_requests_execution_id"),
        "approval_requests",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_requested_at"),
        "approval_requests",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_task_name"),
        "approval_requests",
        ["task_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_workflow_name"),
        "approval_requests",
        ["workflow_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_requests_workflow_namespace"),
        "approval_requests",
        ["workflow_namespace"],
        unique=False,
    )
    op.create_index(
        "ix_approvals_status_requested",
        "approval_requests",
        ["status", "requested_at"],
        unique=False,
    )
    op.create_table(
        "execution_events",
        sa.Column("execution_id", sa.String(), nullable=False),
        sa.Column(
            "id",
            sa.Integer().with_variant(sa.BigInteger(), "postgresql"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "WORKFLOW_SCHEDULED",
                "WORKFLOW_CLAIMED",
                "WORKFLOW_STARTED",
                "WORKFLOW_COMPLETED",
                "WORKFLOW_FAILED",
                "WORKFLOW_PAUSED",
                "WORKFLOW_RESUMING",
                "WORKFLOW_RESUMED",
                "WORKFLOW_RESUME_SCHEDULED",
                "WORKFLOW_RESUME_CLAIMED",
                "WORKFLOW_CANCELLING",
                "WORKFLOW_CANCELLED",
                "TASK_STARTED",
                "TASK_COMPLETED",
                "TASK_FAILED",
                "TASK_PAUSED",
                "TASK_RESUMED",
                "TASK_PROGRESS",
                "TASK_AWAITING_APPROVAL",
                "TASK_APPROVED",
                "TASK_REJECTED",
                "TASK_RETRY_STARTED",
                "TASK_RETRY_COMPLETED",
                "TASK_RETRY_FAILED",
                "TASK_FALLBACK_STARTED",
                "TASK_FALLBACK_COMPLETED",
                "TASK_FALLBACK_FAILED",
                "TASK_ROLLBACK_STARTED",
                "TASK_ROLLBACK_COMPLETED",
                "TASK_ROLLBACK_FAILED",
                name="executioneventtype",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["executions.execution_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_events_execution_id"),
        "execution_events",
        ["execution_id"],
        unique=False,
    )
    op.create_table(
        "worker_resources_gpus",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("memory_total", sa.BigInteger(), nullable=False),
        sa.Column("memory_available", sa.BigInteger(), nullable=False),
        sa.Column("resources_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resources_id"],
            ["worker_resources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worker_resources_gpus")
    op.drop_index(op.f("ix_execution_events_execution_id"), table_name="execution_events")
    op.drop_table("execution_events")
    op.drop_index("ix_approvals_status_requested", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_workflow_namespace"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_workflow_name"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_task_name"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_requested_at"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_execution_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("idx_agent_sessions_agent_started", table_name="agent_sessions")
    op.drop_index("idx_agent_sessions_agent", table_name="agent_sessions")
    op.drop_table("agent_sessions")
    op.drop_table("worker_runtimes")
    op.drop_index(op.f("ix_worker_resources_worker_name"), table_name="worker_resources")
    op.drop_table("worker_resources")
    op.drop_index(op.f("ix_worker_packages_worker_name"), table_name="worker_packages")
    op.drop_table("worker_packages")
    op.drop_index("idx_schedule_workflow_id", table_name="schedules")
    op.drop_index("idx_schedule_status_next_run", table_name="schedules")
    op.drop_index("idx_schedule_status", table_name="schedules")
    op.drop_index("idx_schedule_next_run_at", table_name="schedules")
    op.drop_table("schedules")
    op.drop_table("principal_roles")
    op.drop_index(op.f("ix_executions_workflow_namespace"), table_name="executions")
    op.drop_index(op.f("ix_executions_workflow_name"), table_name="executions")
    op.drop_index(op.f("ix_executions_workflow_id"), table_name="executions")
    op.drop_index("idx_execution_worker_name", table_name="executions")
    op.drop_index("idx_execution_state_worker", table_name="executions")
    op.drop_index("idx_execution_state", table_name="executions")
    op.drop_index("idx_execution_schedule_id", table_name="executions")
    op.drop_table("executions")
    op.drop_table("api_keys")
    op.drop_index("ix_workflow_namespace_name", table_name="workflows")
    op.drop_table("workflows")
    op.drop_table("workers")
    op.drop_table("services")
    op.drop_table("secrets")
    op.drop_table("roles")
    op.drop_table("principals")
    op.drop_table("configs")
    op.drop_table("agents")
    # ### end Alembic commands ###
