"""Run-result persistence and RESULTS.md rendering.

Every run JSON records the machine spec and localhost HTTP RTT so figures
transfer: the per-execution delivery ceiling is RTT-bound (≈50 frames per
worker-flusher round trip), not CPU-bound.
"""

from __future__ import annotations

import json
import platform
import time
from pathlib import Path

import psutil

PERF_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = PERF_ROOT / "results"
RESULTS_MD = PERF_ROOT / "RESULTS.md"


def machine_spec() -> dict:
    cpu_model = ""
    try:
        for line in Path("/proc/cpuinfo").read_text().splitlines():
            if line.lower().startswith("model name"):
                cpu_model = line.split(":", 1)[1].strip()
                break
    except OSError:
        pass
    disk = psutil.disk_usage(str(PERF_ROOT))
    return {
        "platform": platform.platform(),
        "python": platform.python_version(),
        "cpu_model": cpu_model or platform.processor(),
        "cpu_count": psutil.cpu_count(),
        "ram_bytes": psutil.virtual_memory().total,
        "disk_total_bytes": disk.total,
    }


def write_run(test: str, run_name: str, payload: dict) -> Path:
    """Persist one run's results as results/<test>/<run_name>-<ts>.json."""
    out_dir = RESULTS_DIR / test
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d-%H%M%S")
    path = out_dir / f"{run_name}-{stamp}.json"
    record = {
        "test": test,
        "run": run_name,
        "recorded_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "machine": machine_spec(),
        **payload,
    }
    path.write_text(json.dumps(record, indent=2, default=str) + "\n")
    render_results_md()
    return path


def render_results_md():
    """Regenerate RESULTS.md from the latest run of each test.

    A run participates in the summary table when it carries the keys
    ``gate``, ``measured``, and ``passed``; other runs are listed as raw
    data points.
    """
    latest: dict[str, dict] = {}
    all_runs: list[Path] = sorted(RESULTS_DIR.glob("*/*.json"))
    for path in all_runs:
        try:
            record = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        latest[record.get("test", path.parent.name)] = record

    lines = [
        "# Progress-Streaming Perf Results",
        "",
        "Generated by `tests/perf/fixtures/harness/report.py` — do not edit by hand.",
        "Latest run per test; raw runs live in `results/<test>/`.",
        "",
        "| Test | Gate | Measured | Pass | Sealed | DB | Machine |",
        "|---|---|---|---|---|---|---|",
    ]
    for test in sorted(latest):
        r = latest[test]
        machine = r.get("machine", {})
        cpu = machine.get("cpu_model", "?")
        cores = machine.get("cpu_count", "?")
        lines.append(
            "| {test} | {gate} | {measured} | {passed} | {sealed} | {db} | {mach} |".format(
                test=test,
                gate=r.get("gate", "—"),
                measured=r.get("measured", "—"),
                passed={True: "✅", False: "❌"}.get(r.get("passed"), "—"),
                sealed={True: "yes", False: "no"}.get(r.get("sealed"), "—"),
                db=r.get("database", "—"),
                mach=f"{cpu} ×{cores}",
            ),
        )
    lines.append("")
    RESULTS_MD.write_text("\n".join(lines))
